"""add extracted_data to email_requests

Revision ID: 20a676fe8a38
Revises: bea263f80ee5
Create Date: 2026-03-19 00:57:07.655995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a676fe8a38'
down_revision: Union[str, Sequence[str], None] = 'bea263f80ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_requests', sa.Column('extracted_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_requests', 'extracted_data')
    # ### end Alembic commands ###
