"""add email_requests table

Revision ID: 70880be8dd5d
Revises: c740a66c4ad2
Create Date: 2026-03-18 23:33:08.528090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70880be8dd5d'
down_revision: Union[str, Sequence[str], None] = 'c740a66c4ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('folder', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_requests')),
    sa.UniqueConstraint('message_id', name=op.f('uq_email_requests_message_id'))
    )
    op.create_index('ix_email_requests_status', 'email_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_requests_status', table_name='email_requests')
    op.drop_table('email_requests')
    # ### end Alembic commands ###
