"""add quote_requests table

Revision ID: 98e0cffdcc69
Revises: 20a676fe8a38
Create Date: 2026-03-19 01:23:47.603630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e0cffdcc69'
down_revision: Union[str, Sequence[str], None] = '20a676fe8a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email_request_id', sa.UUID(), nullable=False),
    sa.Column('request_index', sa.Integer(), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_identifier', sa.String(), nullable=True),
    sa.Column('client_email', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_request_id'], ['email_requests.id'], name=op.f('fk_quote_requests_email_request_id_email_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_requests')),
    sa.UniqueConstraint('email_request_id', 'request_index', name='uq_quote_requests_email_request_id_request_index')
    )
    op.create_index('ix_quote_requests_email_request_id', 'quote_requests', ['email_request_id'], unique=False)
    op.create_index('ix_quote_requests_status', 'quote_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quote_requests_status', table_name='quote_requests')
    op.drop_index('ix_quote_requests_email_request_id', table_name='quote_requests')
    op.drop_table('quote_requests')
    # ### end Alembic commands ###
