"""add cleaned_content to email_requests

Revision ID: bea263f80ee5
Revises: 70880be8dd5d
Create Date: 2026-03-19 00:02:57.261604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea263f80ee5'
down_revision: Union[str, Sequence[str], None] = '70880be8dd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_requests', sa.Column('cleaned_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_requests', 'cleaned_content')
    # ### end Alembic commands ###
